name: Bing_Wallpaper_Download

on:
  schedule:
    - cron: "1 0 * * *"
  workflow_dispatch:

jobs:
  play:
    runs-on: ubuntu-latest
    env: # 设置整个 job 的环境变量
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Npm install
        run: npm install
      - name: Run Project
        run: npm run start
      - name: Commit files
        run: |
          git config --local user.email "exposir@foxmail.com"
          git config --local user.name "exposir"
          git pull
          git add ./
          git commit -m "Update Bing wallpaper for $(date +'%Y-%m-%d')"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
